"""Database upgrade1

Revision ID: 2a8ac3ce4c7a
Revises: 416bd64b79d5
Create Date: 2023-06-14 11:48:31.687020

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2a8ac3ce4c7a'
down_revision = '416bd64b79d5'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
