"""Database upgrade3

Revision ID: 776f87393deb
Revises: fd1687fdcae1
Create Date: 2023-06-14 11:56:42.114535

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '776f87393deb'
down_revision = 'fd1687fdcae1'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
