"""Database upgrade2

Revision ID: fd1687fdcae1
Revises: 2a8ac3ce4c7a
Create Date: 2023-06-14 11:55:52.100884

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'fd1687fdcae1'
down_revision = '2a8ac3ce4c7a'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
